### ISSUE TITLE
k3sにargoCDからtraefikを導入時にエラーがでる

### ISSUE THREAD

**Issue by HirokiYoshida837** [HirokiYoshida837/ouchi-k8s#3]
argocdからhelmチャートをインストールしようとしてエラー。

```bash
~/k3s/argocd$ kubectl get pods -n kube-system
NAME                                      READY   STATUS             RESTARTS      AGE
coredns-7c444649cb-bknlx                  1/1     Running            0             8m30s
local-path-provisioner-5d56847996-cpsp5   1/1     Running            0             8m30s
metrics-server-7b67f64457-c7sjp           1/1     Running            0             8m30s
helm-install-traefik-crd-tnlwj            0/1     Completed          0             3m25s
helm-install-traefik-bhlfn                0/1     CrashLoopBackOff   5 (15s ago)   3m25s
````

podのログをみてみたらこんな感じ。

```
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --set-string 'global.systemDefaultRegistry=%{SYSTEM_DEFAULT_REGISTRY_RAW}%' traefik https://10.43.0.1:443/static/charts/traefik-20.3.1+up20.3.0.tgz --values /config/values-01_HelmChart.yaml
Error: INSTALLATION FAILED: YAML parse error on traefik/templates/deployment.yaml: error converting YAML to JSON: yaml: line 40: found character that cannot start any token
```

**Comment by HirokiYoshida837** [comment]
元のhelmチャートはこのあたりかな？

https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/deployment.yaml

**Comment by HirokiYoshida837** [comment]
一旦、k3s側でtraefik投入し直し。

ログを見てみる

```
kubectl -n kube-system logs helm-install-traefik-ck9w2
if [[ ${KUBERNETES_SERVICE_HOST} =~ .*:.* ]]; then
        echo "KUBERNETES_SERVICE_HOST is using IPv6"
        CHART="${CHART//%\{KUBERNETES_API\}%/[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}}"
else
        CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
fi

set +v -x
+ [[ '' != \t\r\u\e ]]
+ export HELM_HOST=127.0.0.1:44134
+ HELM_HOST=127.0.0.1:44134
+ tiller --listen=127.0.0.1:44134 --storage=secret
+ helm_v2 init --skip-refresh --client-only --stable-repo-url https://charts.helm.sh/stable/
[main] 2023/04/12 15:46:15 Starting Tiller v2.17.0 (tls=false)
[main] 2023/04/12 15:46:15 GRPC listening on 127.0.0.1:44134
[main] 2023/04/12 15:46:15 Probes listening on :44135
[main] 2023/04/12 15:46:15 Storage driver is Secret
[main] 2023/04/12 15:46:15 Max history per release is 0
Creating /home/klipper-helm/.helm 
Creating /home/klipper-helm/.helm/repository 
Creating /home/klipper-helm/.helm/repository/cache 
Creating /home/klipper-helm/.helm/repository/local 
Creating /home/klipper-helm/.helm/plugins 
Creating /home/klipper-helm/.helm/starters 
Creating /home/klipper-helm/.helm/cache/archive 
Creating /home/klipper-helm/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://charts.helm.sh/stable/ 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /home/klipper-helm/.helm.
Not installing Tiller due to 'client-only' flag having been set
++ ++ jq -r '.Releases | length'timeout 
-s KILL 30 helm_v2 ls --all '^traefik$' --output json
[storage] 2023/04/12 15:46:15 listing all releases with filter
+ V2_CHART_EXISTS=
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ [[ -f /config/ca-file.pem ]]
+ [[ -n '' ]]
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/traefik.tgz.base64
+ CHART_PATH=/tmp/traefik.tgz
+ [[ ! -f /chart/traefik.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
+ echo 'chart path is a url, skipping repo update'
chart path is a url, skipping repo update
+ helm_v3 repo remove stable
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --set-string global.systemDefaultRegistry= traefik https://10.43.0.1:443/static/charts/traefik-20.3.1+up20.3.0.tgz --values /config/values-01_HelmChart.yaml
NAME: traefik
LAST DEPLOYED: Wed Apr 12 15:46:15 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Traefik Proxy v2.9.4 has been deployed successfully 
on kube-system namespace !
+ exit
```

**Comment by HirokiYoshida837** [comment]
k3sによって配置されているyamlはこれ

> sudo cat /var/lib/rancher/k3s/server/manifests/traefik.yaml

```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-20.3.1+up20.3.0.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-20.3.1+up20.3.0.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      name: "rancher/mirrored-library-traefik"
      tag: "2.9.4"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"
```
